### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by codeaudit** [naibaf7/caffe_neural_tool#2]
src/benchmark.cpp: In function ‘void caffe_neural::FillNet(boost::shared_ptrcaffe::Layer<float >, boost::shared_ptrcaffe::Layer<float >, int)’:
src/benchmark.cpp:53:48: error: no matching function for call to ‘caffe::MemoryDataLayer<float>::AddMatVector(std::vectorcv::Mat&, std::vector<int>&)’
     data_layer_ptr->AddMatVector(images, labels);
                                                ^
src/benchmark.cpp:53:48: note: candidate is:
In file included from ../caffe/include/caffe/vision_layers.hpp:11:0,
                 from ../caffe/include/caffe/caffe.hpp:23,
                 from include/caffe_neural_tool.hpp:20,
                 from include/benchmark.hpp:11,
                 from src/benchmark.cpp:8:
../caffe/include/caffe/data_layers.hpp:281:16: note: void caffe::MemoryDataLayer<Dtype>::AddMatVector(const std::vectorcv::Mat&, const std::vector<long int>&) [with Dtype = float]
   virtual void AddMatVector(const vectorcv::Mat& mat_vector,
                ^
../caffe/include/caffe/data_layers.hpp:281:16: note:   no known conversion for argument 2 from ‘std::vector<int>’ to ‘const std::vector<long int>&’
src/benchmark.cpp:82:43: error: no matching function for call to ‘caffe::MemoryDataLayer<float>::AddMatVector(std::vectorcv::Mat&, std::vector<int>&)’
     layer_ptr->AddMatVector(images, labels);
                                           ^
src/benchmark.cpp:82:43: note: candidate is:
In file included from ../caffe/include/caffe/vision_layers.hpp:11:0,
                 from ../caffe/include/caffe/caffe.hpp:23,
                 from include/caffe_neural_tool.hpp:20,
                 from include/benchmark.hpp:11,
                 from src/benchmark.cpp:8:
../caffe/include/caffe/data_layers.hpp:281:16: note: void caffe::MemoryDataLayer<Dtype>::AddMatVector(const std::vectorcv::Mat&, const std::vector<long int>&) [with Dtype = float]
   virtual void AddMatVector(const vectorcv::Mat& mat_vector,
                ^
../caffe/include/caffe/data_layers.hpp:281:16: note:   no known conversion for argument 2 from ‘std::vector<int>’ to ‘const std::vector<long int>&’
src/benchmark.cpp: In function ‘int caffe_neural::Benchmark(caffe_neural::ToolParam&, CommonSettings&)’:
src/benchmark.cpp:121:9: error: ‘GetSolver’ is not a member of ‘caffe’
         caffe::GetSolver<float>(solver_param));
         ^
src/benchmark.cpp:121:26: error: expected primary-expression before ‘float’
         caffe::GetSolver<float>(solver_param));
                          ^
In file included from ../ViennaCL/viennacl/ocl/backend.hpp:27:0,
                 from ../ViennaCL/viennacl/backend/opencl.hpp:28,
                 from ../caffe/include/caffe/greentea/greentea.hpp:33,
                 from ../caffe/include/caffe/common.hpp:25,
                 from ../caffe/include/caffe/util/io.hpp:9,
                 from include/caffe_neural_tool.hpp:18,
                 from include/benchmark.hpp:11,
                 from src/benchmark.cpp:8:
../ViennaCL/viennacl/ocl/enqueue.hpp: In instantiation of ‘void viennacl::ocl::enqueue(KernelType&, const viennacl::ocl::command_queue&) [with KernelType = viennacl::ocl::kernel]’:
../ViennaCL/viennacl/ocl/enqueue.hpp:133:37:   required from ‘void viennacl::ocl::enqueue(KernelType&) [with KernelType = viennacl::ocl::kernel]’
../ViennaCL/viennacl/device_specific/templates/row_wise_reduction_template.hpp:292:35:   required from here
../ViennaCL/viennacl/ocl/enqueue.hpp:73:80: warning: ‘cl_int clEnqueueTask(cl_command_queue, cl_kernel, cl_uint, _cl_event\* const_, _cl_event_*)’ is deprecated (declared at /usr/include/CL/cl.h:1372) [-Wdeprecated-declarations]
       err = clEnqueueTask(queue.handle().get(), k.handle().get(), 0, NULL, NULL);

**Comment by naibaf7** [comment]
Known issue. The current version of OpenCL Caffe breaks compability with the Caffe Neural Models and Caffe Neural Tool. There will be a replacement in Python for both coming up soon.
The fix is to use an older commit of Caffe-OpenCL (Greentea), notably I'd currently recommend to use:
Models: dbb06d8352aa9c2ba99458cb9e9068500ebacc11
Tool: 780e7dd72e4f88c80729e2b33d6c0137d479016a
Greentea/Caffe: f84c2a4fb8d633bc7d8fc9771eb06a3cf2215212

That can be enforced by using different methods:
http://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository

**Comment by naibaf7** [comment]
I took some time to adapt the Caffe Neural Tool to the newest version of my Caffe/Greentea library.
@codeaudit 
You can now test the benchmark scripts. You may have to edit the scripts (benchmark_sk.sh benchmark_u.sh and benchmark_usk.sh) to use the right device in your computer.
The results will be stored as CSV in the folders sk_benchmark etc.

I am always interested in benchmark values of devices that I have not tested myself yet!
