### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by manishrdmishra** [naibaf7/caffe_neural_tool#3]
I  build naibaf7/caffe using cmake. it was successful .
When I am trying to build caffe_neural_tool using make command , I am getting the following error.

---

CXX -o build/obj/rel/src/benchmark.o
g++ -Wall -std=c++11 -fopenmp -Wno-sign-compare -DUSE_OPENCV -DUSE_GREENTEA -DVIENNACL_WITH_OPENCL -O0 -g -Iinclude -I../caffe/include -I../caffe/caffe -I../caffe/caffe/src -I../caffe/build/src -I../caffe/build/include/caffe/proto  -I../ViennaCL -c -o build/obj/rel/src/benchmark.o src/benchmark.cpp
In file included from include/caffe_neural_tool.hpp:20:0,
                 from include/benchmark.hpp:11,
                 from src/benchmark.cpp:8:
../caffe/include/caffe/util/io.hpp:12:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
 #include "caffe/proto/caffe.pb.h"
                                  ^
compilation terminated.

---

I checked caffe.pb.h file is present in /caffe_root/build/src/caffe/proto/ directory. 
Please let me know how can I resolve this compilation issue. Any help would be grateful. 
Thanks!!

**Comment by naibaf7** [comment]
You can run ./protoc_generator.sh in the caffe directory and then it should work.
